### PR TITLE
Reduce unnecessary binding

### PR DESCRIPTION
**Pull request by LuoZijun**

### CODE REVIEW

**Comment by yaa110** [comment]
CI error:

```
error[E0412]: cannot find type `SSL_CTX` in this scope
```

**Comment by LuoZijun** [comment]
@yaa110 Sorry, not tested under Linux. I will test it in Linux later.

**Comment by yaa110** [comment]
thank you for the PR. However, it adds external dependencies and manual implementations to the crate which makes the maintenance of the crate harder.

**Comment by LuoZijun** [comment]
Ok, i will close this PR.

**Pull request closed without merging**
